INSERT INTO g2department VALUES ('Claims Department', 2301, 'Varsha', 'Life Insurance Corporation of India') ;
INSERT INTO g2department VALUES ('Investment Department', 2302, 'Harsha', 'HDFC Life Insurance Co. Ltd') ;
INSERT INTO g2department VALUES ('Claims Department', 2303, 'Sankalp', 'Max Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Legal Department', 2304, 'Saketh', 'ICICI Prudential Life Insurance Co. Ltd') ;
INSERT INTO g2department VALUES ('Legal Department', 2305, 'Rupa', 'Kotak Mahindra Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Claims and audit loss Department', 2306, 'Rupesh', 'Aditya Birla SunLife Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Legal Department', 2307, 'Dattareya', 'TATA AIA Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Underwriting Department', 2308, 'Anandi', 'SBI Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Reinsurance Department', 2309, 'Anand', 'Exide Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Claims and audit Department', 2310, 'Bhanushali', 'Bajaj Allianz Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Claims Department', 2311, 'Harshad', 'PNB MetLife India Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Claims and audit loss Department', 2312, 'raghu', 'Reliance Nippon Life Insurance Company Limited') ;
INSERT INTO g2department VALUES ('Legal Department', 2313, 'ramu', 'Aviva Life Insurance Company India Ltd.') ;
INSERT INTO g2department VALUES ('Claims and audit Department', 2314, 'krishna', 'Sahara India Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Audit Department', 2315, 'ravi', 'Shriram Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Claims and audit profit Department', 2316, 'agni', 'Bharti AXA Life Insurance Company Ltd') ;
INSERT INTO g2department VALUES ('Accounting Department', 2317, 'raju', 'Future Generali India Life Insurance Company Limited,') ;
INSERT INTO g2department VALUES ('Audit Department', 2318, 'ramesh', 'IDBI Federal Life Insurance Company Limited') ;
INSERT INTO g2department VALUES ('Underwriting Department', 2319, 'suresh', 'Canara HSBC Oriental Bank of Commerce Life Insurance Company Limited') ;
INSERT INTO g2department VALUES ('Actuarial and Statistical Department', 2320, 'naresh', 'Aegon Life Insurance Company Limited') ;
INSERT INTO g2department VALUES ('Underwriting Department', 2321, 'mahesh', 'Pramerica Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Marketing Department', 2322, 'sanketh', 'Star Union Dai-Ichi Life Insurance Co. Ltd.') ;
INSERT INTO g2department VALUES ('Claims and audit profit Department', 2323, 'saleem', 'IndiaFirst Life Insurance Company Ltd.,') ;
INSERT INTO g2department VALUES ('Agency Department', 2324, 'akhil', 'Edelweiss Tokio Life Insurance Company Limited') ;
INSERT INTO g2department VALUES ('Legal Department', 2325, 'aman', 'Adani Insurance Company') ;
INSERT INTO g2department VALUES ('claim department', 2326, 'amaresh', 'green india company') ;
INSERT INTO g2department VALUES ('claim department', 2327, 'ameer', 'go india company') ;
