INSERT INTO g2vehicle_service VALUES ('Claims Department', 'Astar', 'Delhi', 1234567890, 'Ramesh', 'Full service', 2301, 'Life Insurance Corporation of India') ;
INSERT INTO g2vehicle_service VALUES ('Investment Department', 'Bstar', 'Jammu', 7889455612, 'Suresh', 'Full service', 2302, 'HDFC Life Insurance Co. Ltd') ;
INSERT INTO g2vehicle_service VALUES ('Claims Department', 'Cstar', 'srinagr', 1223455678, 'Naresh', 'half service', 2303, 'Max Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Legal Department', 'Dstar', 'Kashmir', 988765543, 'Mahesh', 'Full service', 2304, 'ICICI Prudential Life Insurance Co. Ltd') ;
INSERT INTO g2vehicle_service VALUES ('Legal Department', '1Star', 'Gandhinagar', 1245788956, 'Ajay', 'half service', 2305, 'Kotak Mahindra Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Claims and audit loss Department', '5star', 'Hyderabad', 4758695898, 'Nani', 'Full service', 2306, 'Aditya Birla SunLife Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Legal Department', 'A1', 'Pune', 4152639685, 'Kumar', 'Full service', 2307, 'TATA AIA Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Underwriting Department', 'B1', 'Bhopal', 4578963225, 'Ajith', 'half service', 2308, 'SBI Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Reinsurance Department', 'C1', 'Patna', 8596875498, 'Vijay', 'Full service', 2309, 'Exide Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Claims and audit Department', 'Wheels', 'Amaravathi', 9865325487, 'Anthony', 'Full service', 2310, 'Bajaj Allianz Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Claims Department', 'Abc', 'Agra', 2927288465, 'Rajini', 'Full service', 2311, 'PNB MetLife India Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Claims and audit loss Department', 'xyz', 'Amritsar', 717273767, 'Roshan', 'half service', 2312, 'Reliance Nippon Life Insurance Company Limited') ;
INSERT INTO g2vehicle_service VALUES ('Legal Department', 'mno', 'Kolkata', 8182838485, 'Devi', 'Full service', 2313, 'Aviva Life Insurance Company India Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Claims and audit Department', 'pqr', 'Cyberabad', 9495969897, 'Deepika', 'Full service', 2314, 'Sahara India Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Audit Department', 'stu', 'Chennai', 8184878582, 'Devansh', 'half service', 2315, 'Shriram Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Claims and audit profit Department', 'Stunt', 'Bangalore', 7475767879, 'Sriansh', 'Full service', 2316, 'Bharti AXA Life Insurance Company Ltd') ;
INSERT INTO g2vehicle_service VALUES ('Accounting Department', 'lv', 'Tirupathi', 4548494642, 'Rudranch', 'Full service', 2317, 'Future Generali India Life Insurance Company Limited,') ;
INSERT INTO g2vehicle_service VALUES ('Audit Department', 'kub', 'Agertala', 9787574767, 'Vedanch', 'half service', 2318, 'IDBI Federal Life Insurance Company Limited') ;
INSERT INTO g2vehicle_service VALUES ('Underwriting Department', 'cub', 'Silchar', 6598685947, 'Devanch', 'Full service', 2319, 'Canara HSBC Oriental Bank of Commerce Life Insurance Company Limited') ;
INSERT INTO g2vehicle_service VALUES ('Actuarial and Statistical Department', 'isd', 'Kanchi', 1245865957, 'Sivanch', 'Full service', 2320, 'Aegon Life Insurance Company Limited') ;
INSERT INTO g2vehicle_service VALUES ('Underwriting Department', 'sto', 'Tricy', 3265854878, 'Amir', 'half service', 2321, 'Pramerica Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Marketing Department', 'poc', 'Kanyakumari', 1938284675, 'Khabir', 'Full service', 2322, 'Star Union Dai-Ichi Life Insurance Co. Ltd.') ;
INSERT INTO g2vehicle_service VALUES ('Claims and audit profit Department', 'klm', 'Kharakpur', 3719582648, 'Rathod', 'half service', 2323, 'IndiaFirst Life Insurance Company Ltd.,') ;
INSERT INTO g2vehicle_service VALUES ('Agency Department', 'cmr', 'Ganga', 9156874253, 'Salam', 'Full service', 2324, 'Edelweiss Tokio Life Insurance Company Limited') ;
INSERT INTO g2vehicle_service VALUES ('Legal Department', 'sid', 'Hubli', 5684269810, 'Salim', 'Full service', 2325, 'Adani Insurance Company') ;
INSERT INTO g2vehicle_service VALUES ('claim department', 'sriram', 'vizag', '', '', '', 2326, 'green india company') ;
INSERT INTO g2vehicle_service VALUES ('claim department', 'l and t', 'amaravathi', '', '', '', 2327, 'go india company') ;
